source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CommonLib_Example', :exclusive => true do
  pod "CommonLib", :path => "../"
end

target 'CommonLib_Tests', :exclusive => true do
  pod "CommonLib", :path => "../"

  
end
