// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "ConfigItem.pb.h"
// @@protoc_insertion_point(imports)

@class Config;
@class ConfigBuilder;
@class ConfigItem;
@class ConfigItemBuilder;



@interface ConfigRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Config_items @"items"
@interface Config : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * itemsArray;
}
@property (readonly, strong) NSArray * items;
- (ConfigItem*)itemsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ConfigBuilder*) builder;
+ (ConfigBuilder*) builder;
+ (ConfigBuilder*) builderWithPrototype:(Config*) prototype;
- (ConfigBuilder*) toBuilder;

+ (Config*) parseFromData:(NSData*) data;
+ (Config*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Config*) parseFromInputStream:(NSInputStream*) input;
+ (Config*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Config*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Config*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ConfigBuilder : PBGeneratedMessageBuilder {
@private
  Config* resultConfig;
}

- (Config*) defaultInstance;

- (ConfigBuilder*) clear;
- (ConfigBuilder*) clone;

- (Config*) build;
- (Config*) buildPartial;

- (ConfigBuilder*) mergeFrom:(Config*) other;
- (ConfigBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ConfigBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)items;
- (ConfigItem*)itemsAtIndex:(NSUInteger)index;
- (ConfigBuilder *)addItems:(ConfigItem*)value;
- (ConfigBuilder *)setItemsArray:(NSArray *)array;
- (ConfigBuilder *)clearItems;
@end


// @@protoc_insertion_point(global_scope)
