// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "SwDesc.pb.h"
#import "ResourceByte.pb.h"
// @@protoc_insertion_point(imports)

@class Para;
@class ParaBuilder;
@class ResourceByte;
@class ResourceByteBuilder;
@class ResourceDataFile;
@class ResourceDataFileBuilder;
@class ResourceQuality;
@class ResourceQualityBuilder;
@class SignRectangle;
@class SignRectangleBuilder;
@class SwAnimation;
@class SwAnimationBuilder;
@class SwCompsiteAnimation;
@class SwCompsiteAnimationBuilder;
@class SwDesc;
@class SwDescBuilder;
@class SwFrame;
@class SwFrameBuilder;



@interface ResourceDataFileRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define ResourceDataFile_desc @"desc"
#define ResourceDataFile_bytes @"bytes"
#define ResourceDataFile_quality @"quality"
@interface ResourceDataFile : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasDesc_:1;
  SwDesc* desc;
  NSMutableArray * bytesArray;
  NSMutableArray * qualityArray;
}
- (BOOL) hasDesc;
@property (readonly, strong) SwDesc* desc;
@property (readonly, strong) NSArray * bytes;
@property (readonly, strong) NSArray * quality;
- (ResourceByte*)bytesAtIndex:(NSUInteger)index;
- (ResourceQuality*)qualityAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResourceDataFileBuilder*) builder;
+ (ResourceDataFileBuilder*) builder;
+ (ResourceDataFileBuilder*) builderWithPrototype:(ResourceDataFile*) prototype;
- (ResourceDataFileBuilder*) toBuilder;

+ (ResourceDataFile*) parseFromData:(NSData*) data;
+ (ResourceDataFile*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResourceDataFile*) parseFromInputStream:(NSInputStream*) input;
+ (ResourceDataFile*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResourceDataFile*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResourceDataFile*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ResourceDataFileBuilder : PBGeneratedMessageBuilder {
@private
  ResourceDataFile* resultResourceDataFile;
}

- (ResourceDataFile*) defaultInstance;

- (ResourceDataFileBuilder*) clear;
- (ResourceDataFileBuilder*) clone;

- (ResourceDataFile*) build;
- (ResourceDataFile*) buildPartial;

- (ResourceDataFileBuilder*) mergeFrom:(ResourceDataFile*) other;
- (ResourceDataFileBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResourceDataFileBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDesc;
- (SwDesc*) desc;
- (ResourceDataFileBuilder*) setDesc:(SwDesc*) value;
- (ResourceDataFileBuilder*) setDescBuilder:(SwDescBuilder*) builderForValue;
- (ResourceDataFileBuilder*) mergeDesc:(SwDesc*) value;
- (ResourceDataFileBuilder*) clearDesc;

- (NSMutableArray *)bytes;
- (ResourceByte*)bytesAtIndex:(NSUInteger)index;
- (ResourceDataFileBuilder *)addBytes:(ResourceByte*)value;
- (ResourceDataFileBuilder *)setBytesArray:(NSArray *)array;
- (ResourceDataFileBuilder *)clearBytes;

- (NSMutableArray *)quality;
- (ResourceQuality*)qualityAtIndex:(NSUInteger)index;
- (ResourceDataFileBuilder *)addQuality:(ResourceQuality*)value;
- (ResourceDataFileBuilder *)setQualityArray:(NSArray *)array;
- (ResourceDataFileBuilder *)clearQuality;
@end

#define ResourceQuality_name @"name"
#define ResourceQuality_value @"value"
@interface ResourceQuality : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasValue_:1;
  BOOL hasName_:1;
  SInt32 value;
  NSString* name;
}
- (BOOL) hasName;
- (BOOL) hasValue;
@property (readonly, strong) NSString* name;
@property (readonly) SInt32 value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResourceQualityBuilder*) builder;
+ (ResourceQualityBuilder*) builder;
+ (ResourceQualityBuilder*) builderWithPrototype:(ResourceQuality*) prototype;
- (ResourceQualityBuilder*) toBuilder;

+ (ResourceQuality*) parseFromData:(NSData*) data;
+ (ResourceQuality*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResourceQuality*) parseFromInputStream:(NSInputStream*) input;
+ (ResourceQuality*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResourceQuality*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResourceQuality*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ResourceQualityBuilder : PBGeneratedMessageBuilder {
@private
  ResourceQuality* resultResourceQuality;
}

- (ResourceQuality*) defaultInstance;

- (ResourceQualityBuilder*) clear;
- (ResourceQualityBuilder*) clone;

- (ResourceQuality*) build;
- (ResourceQuality*) buildPartial;

- (ResourceQualityBuilder*) mergeFrom:(ResourceQuality*) other;
- (ResourceQualityBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResourceQualityBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (ResourceQualityBuilder*) setName:(NSString*) value;
- (ResourceQualityBuilder*) clearName;

- (BOOL) hasValue;
- (SInt32) value;
- (ResourceQualityBuilder*) setValue:(SInt32) value;
- (ResourceQualityBuilder*) clearValue;
@end


// @@protoc_insertion_point(global_scope)
