// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "SwFrame.pb.h"
#import "SignRectangle.pb.h"
#import "Para.pb.h"
// @@protoc_insertion_point(imports)

@class Para;
@class ParaBuilder;
@class SignRectangle;
@class SignRectangleBuilder;
@class SwAnimation;
@class SwAnimationBuilder;
@class SwCompsiteAnimation;
@class SwCompsiteAnimationBuilder;
@class SwFrame;
@class SwFrameBuilder;



@interface SwAnimationRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define SwAnimation_name @"name"
#define SwAnimation_frameCount @"frameCount"
#define SwAnimation_timeCount @"timeCount"
#define SwAnimation_frames @"frames"
#define SwAnimation_signRectangles @"signRectangles"
#define SwAnimation_paras @"paras"
#define SwAnimation_width @"width"
#define SwAnimation_height @"height"
#define SwAnimation_scaleX @"scaleX"
#define SwAnimation_scaleY @"scaleY"
#define SwAnimation_compsiteAnimations @"compsiteAnimations"
@interface SwAnimation : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasWidth_:1;
  BOOL hasHeight_:1;
  BOOL hasScaleX_:1;
  BOOL hasScaleY_:1;
  BOOL hasName_:1;
  BOOL hasFrameCount_:1;
  BOOL hasTimeCount_:1;
  SInt32 width;
  SInt32 height;
  SInt32 scaleX;
  SInt32 scaleY;
  NSString* name;
  UInt32 frameCount;
  UInt32 timeCount;
  NSMutableArray * framesArray;
  NSMutableArray * signRectanglesArray;
  NSMutableArray * parasArray;
  NSMutableArray * compsiteAnimationsArray;
}
- (BOOL) hasName;
- (BOOL) hasFrameCount;
- (BOOL) hasTimeCount;
- (BOOL) hasWidth;
- (BOOL) hasHeight;
- (BOOL) hasScaleX;
- (BOOL) hasScaleY;
@property (readonly, strong) NSString* name;
@property (readonly) UInt32 frameCount;
@property (readonly) UInt32 timeCount;
@property (readonly, strong) NSArray * frames;
@property (readonly, strong) NSArray * signRectangles;
@property (readonly, strong) NSArray * paras;
@property (readonly) SInt32 width;
@property (readonly) SInt32 height;
@property (readonly) SInt32 scaleX;
@property (readonly) SInt32 scaleY;
@property (readonly, strong) NSArray * compsiteAnimations;
- (SwFrame*)framesAtIndex:(NSUInteger)index;
- (SignRectangle*)signRectanglesAtIndex:(NSUInteger)index;
- (Para*)parasAtIndex:(NSUInteger)index;
- (SwCompsiteAnimation*)compsiteAnimationsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SwAnimationBuilder*) builder;
+ (SwAnimationBuilder*) builder;
+ (SwAnimationBuilder*) builderWithPrototype:(SwAnimation*) prototype;
- (SwAnimationBuilder*) toBuilder;

+ (SwAnimation*) parseFromData:(NSData*) data;
+ (SwAnimation*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwAnimation*) parseFromInputStream:(NSInputStream*) input;
+ (SwAnimation*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwAnimation*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SwAnimation*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SwAnimationBuilder : PBGeneratedMessageBuilder {
@private
  SwAnimation* resultSwAnimation;
}

- (SwAnimation*) defaultInstance;

- (SwAnimationBuilder*) clear;
- (SwAnimationBuilder*) clone;

- (SwAnimation*) build;
- (SwAnimation*) buildPartial;

- (SwAnimationBuilder*) mergeFrom:(SwAnimation*) other;
- (SwAnimationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SwAnimationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (SwAnimationBuilder*) setName:(NSString*) value;
- (SwAnimationBuilder*) clearName;

- (BOOL) hasFrameCount;
- (UInt32) frameCount;
- (SwAnimationBuilder*) setFrameCount:(UInt32) value;
- (SwAnimationBuilder*) clearFrameCount;

- (BOOL) hasTimeCount;
- (UInt32) timeCount;
- (SwAnimationBuilder*) setTimeCount:(UInt32) value;
- (SwAnimationBuilder*) clearTimeCount;

- (NSMutableArray *)frames;
- (SwFrame*)framesAtIndex:(NSUInteger)index;
- (SwAnimationBuilder *)addFrames:(SwFrame*)value;
- (SwAnimationBuilder *)setFramesArray:(NSArray *)array;
- (SwAnimationBuilder *)clearFrames;

- (NSMutableArray *)signRectangles;
- (SignRectangle*)signRectanglesAtIndex:(NSUInteger)index;
- (SwAnimationBuilder *)addSignRectangles:(SignRectangle*)value;
- (SwAnimationBuilder *)setSignRectanglesArray:(NSArray *)array;
- (SwAnimationBuilder *)clearSignRectangles;

- (NSMutableArray *)paras;
- (Para*)parasAtIndex:(NSUInteger)index;
- (SwAnimationBuilder *)addParas:(Para*)value;
- (SwAnimationBuilder *)setParasArray:(NSArray *)array;
- (SwAnimationBuilder *)clearParas;

- (BOOL) hasWidth;
- (SInt32) width;
- (SwAnimationBuilder*) setWidth:(SInt32) value;
- (SwAnimationBuilder*) clearWidth;

- (BOOL) hasHeight;
- (SInt32) height;
- (SwAnimationBuilder*) setHeight:(SInt32) value;
- (SwAnimationBuilder*) clearHeight;

- (BOOL) hasScaleX;
- (SInt32) scaleX;
- (SwAnimationBuilder*) setScaleX:(SInt32) value;
- (SwAnimationBuilder*) clearScaleX;

- (BOOL) hasScaleY;
- (SInt32) scaleY;
- (SwAnimationBuilder*) setScaleY:(SInt32) value;
- (SwAnimationBuilder*) clearScaleY;

- (NSMutableArray *)compsiteAnimations;
- (SwCompsiteAnimation*)compsiteAnimationsAtIndex:(NSUInteger)index;
- (SwAnimationBuilder *)addCompsiteAnimations:(SwCompsiteAnimation*)value;
- (SwAnimationBuilder *)setCompsiteAnimationsArray:(NSArray *)array;
- (SwAnimationBuilder *)clearCompsiteAnimations;
@end

#define SwCompsiteAnimation_name @"name"
#define SwCompsiteAnimation_targetRid @"targetRid"
#define SwCompsiteAnimation_targetDimension @"targetDimension"
#define SwCompsiteAnimation_targetSignRectangleName @"targetSignRectangleName"
#define SwCompsiteAnimation_targetScaleX @"targetScaleX"
#define SwCompsiteAnimation_targetScaleY @"targetScaleY"
#define SwCompsiteAnimation_sourceSignRectangleName @"sourceSignRectangleName"
@interface SwCompsiteAnimation : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTargetScaleX_:1;
  BOOL hasTargetScaleY_:1;
  BOOL hasName_:1;
  BOOL hasTargetRid_:1;
  BOOL hasTargetDimension_:1;
  BOOL hasTargetSignRectangleName_:1;
  BOOL hasSourceSignRectangleName_:1;
  SInt32 targetScaleX;
  SInt32 targetScaleY;
  NSString* name;
  NSString* targetRid;
  NSString* targetDimension;
  NSString* targetSignRectangleName;
  NSString* sourceSignRectangleName;
}
- (BOOL) hasName;
- (BOOL) hasTargetRid;
- (BOOL) hasTargetDimension;
- (BOOL) hasTargetSignRectangleName;
- (BOOL) hasTargetScaleX;
- (BOOL) hasTargetScaleY;
- (BOOL) hasSourceSignRectangleName;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* targetRid;
@property (readonly, strong) NSString* targetDimension;
@property (readonly, strong) NSString* targetSignRectangleName;
@property (readonly) SInt32 targetScaleX;
@property (readonly) SInt32 targetScaleY;
@property (readonly, strong) NSString* sourceSignRectangleName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SwCompsiteAnimationBuilder*) builder;
+ (SwCompsiteAnimationBuilder*) builder;
+ (SwCompsiteAnimationBuilder*) builderWithPrototype:(SwCompsiteAnimation*) prototype;
- (SwCompsiteAnimationBuilder*) toBuilder;

+ (SwCompsiteAnimation*) parseFromData:(NSData*) data;
+ (SwCompsiteAnimation*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwCompsiteAnimation*) parseFromInputStream:(NSInputStream*) input;
+ (SwCompsiteAnimation*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwCompsiteAnimation*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SwCompsiteAnimation*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SwCompsiteAnimationBuilder : PBGeneratedMessageBuilder {
@private
  SwCompsiteAnimation* resultSwCompsiteAnimation;
}

- (SwCompsiteAnimation*) defaultInstance;

- (SwCompsiteAnimationBuilder*) clear;
- (SwCompsiteAnimationBuilder*) clone;

- (SwCompsiteAnimation*) build;
- (SwCompsiteAnimation*) buildPartial;

- (SwCompsiteAnimationBuilder*) mergeFrom:(SwCompsiteAnimation*) other;
- (SwCompsiteAnimationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SwCompsiteAnimationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (SwCompsiteAnimationBuilder*) setName:(NSString*) value;
- (SwCompsiteAnimationBuilder*) clearName;

- (BOOL) hasTargetRid;
- (NSString*) targetRid;
- (SwCompsiteAnimationBuilder*) setTargetRid:(NSString*) value;
- (SwCompsiteAnimationBuilder*) clearTargetRid;

- (BOOL) hasTargetDimension;
- (NSString*) targetDimension;
- (SwCompsiteAnimationBuilder*) setTargetDimension:(NSString*) value;
- (SwCompsiteAnimationBuilder*) clearTargetDimension;

- (BOOL) hasTargetSignRectangleName;
- (NSString*) targetSignRectangleName;
- (SwCompsiteAnimationBuilder*) setTargetSignRectangleName:(NSString*) value;
- (SwCompsiteAnimationBuilder*) clearTargetSignRectangleName;

- (BOOL) hasTargetScaleX;
- (SInt32) targetScaleX;
- (SwCompsiteAnimationBuilder*) setTargetScaleX:(SInt32) value;
- (SwCompsiteAnimationBuilder*) clearTargetScaleX;

- (BOOL) hasTargetScaleY;
- (SInt32) targetScaleY;
- (SwCompsiteAnimationBuilder*) setTargetScaleY:(SInt32) value;
- (SwCompsiteAnimationBuilder*) clearTargetScaleY;

- (BOOL) hasSourceSignRectangleName;
- (NSString*) sourceSignRectangleName;
- (SwCompsiteAnimationBuilder*) setSourceSignRectangleName:(NSString*) value;
- (SwCompsiteAnimationBuilder*) clearSourceSignRectangleName;
@end


// @@protoc_insertion_point(global_scope)
