// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class ConfigItem;
@class ConfigItemBuilder;



@interface ConfigItemRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define ConfigItem_id @"id"
#define ConfigItem_url @"url"
#define ConfigItem_version @"version"
#define ConfigItem_type @"type"
#define ConfigItem_dir @"dir"
#define ConfigItem_description @"pb_description"
@interface ConfigItem : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasType_:1;
  BOOL hasId_:1;
  BOOL hasUrl_:1;
  BOOL hasVersion_:1;
  BOOL hasDir_:1;
  BOOL hasDescription_:1;
  SInt32 type;
  NSString* id;
  NSString* url;
  NSString* version;
  NSString* dir;
  NSString* pb_description;
}
- (BOOL) hasId;
- (BOOL) hasUrl;
- (BOOL) hasVersion;
- (BOOL) hasType;
- (BOOL) hasDir;
- (BOOL) hasDescription;
@property (readonly, strong) NSString* id;
@property (readonly, strong) NSString* url;
@property (readonly, strong) NSString* version;
@property (readonly) SInt32 type;
@property (readonly, strong) NSString* dir;
@property (readonly, strong) NSString* pb_description;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ConfigItemBuilder*) builder;
+ (ConfigItemBuilder*) builder;
+ (ConfigItemBuilder*) builderWithPrototype:(ConfigItem*) prototype;
- (ConfigItemBuilder*) toBuilder;

+ (ConfigItem*) parseFromData:(NSData*) data;
+ (ConfigItem*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ConfigItem*) parseFromInputStream:(NSInputStream*) input;
+ (ConfigItem*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ConfigItem*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ConfigItem*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ConfigItemBuilder : PBGeneratedMessageBuilder {
@private
  ConfigItem* resultConfigItem;
}

- (ConfigItem*) defaultInstance;

- (ConfigItemBuilder*) clear;
- (ConfigItemBuilder*) clone;

- (ConfigItem*) build;
- (ConfigItem*) buildPartial;

- (ConfigItemBuilder*) mergeFrom:(ConfigItem*) other;
- (ConfigItemBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ConfigItemBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (ConfigItemBuilder*) setId:(NSString*) value;
- (ConfigItemBuilder*) clearId;

- (BOOL) hasUrl;
- (NSString*) url;
- (ConfigItemBuilder*) setUrl:(NSString*) value;
- (ConfigItemBuilder*) clearUrl;

- (BOOL) hasVersion;
- (NSString*) version;
- (ConfigItemBuilder*) setVersion:(NSString*) value;
- (ConfigItemBuilder*) clearVersion;

- (BOOL) hasType;
- (SInt32) type;
- (ConfigItemBuilder*) setType:(SInt32) value;
- (ConfigItemBuilder*) clearType;

- (BOOL) hasDir;
- (NSString*) dir;
- (ConfigItemBuilder*) setDir:(NSString*) value;
- (ConfigItemBuilder*) clearDir;

- (BOOL) hasDescription;
- (NSString*) pb_description;
- (ConfigItemBuilder*) setDescription:(NSString*) value;
- (ConfigItemBuilder*) clearDescription;
@end


// @@protoc_insertion_point(global_scope)
