// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class Para;
@class ParaBuilder;



@interface ParaRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Para_name @"name"
#define Para_value @"value"
@interface Para : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasName_:1;
  BOOL hasValue_:1;
  NSString* name;
  NSString* value;
}
- (BOOL) hasName;
- (BOOL) hasValue;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ParaBuilder*) builder;
+ (ParaBuilder*) builder;
+ (ParaBuilder*) builderWithPrototype:(Para*) prototype;
- (ParaBuilder*) toBuilder;

+ (Para*) parseFromData:(NSData*) data;
+ (Para*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Para*) parseFromInputStream:(NSInputStream*) input;
+ (Para*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Para*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Para*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ParaBuilder : PBGeneratedMessageBuilder {
@private
  Para* resultPara;
}

- (Para*) defaultInstance;

- (ParaBuilder*) clear;
- (ParaBuilder*) clone;

- (Para*) build;
- (Para*) buildPartial;

- (ParaBuilder*) mergeFrom:(Para*) other;
- (ParaBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ParaBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (ParaBuilder*) setName:(NSString*) value;
- (ParaBuilder*) clearName;

- (BOOL) hasValue;
- (NSString*) value;
- (ParaBuilder*) setValue:(NSString*) value;
- (ParaBuilder*) clearValue;
@end


// @@protoc_insertion_point(global_scope)
