// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class ResourceByte;
@class ResourceByteBuilder;



@interface ResourceByteRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define ResourceByte_key @"key"
#define ResourceByte_value @"value"
#define ResourceByte_ext @"ext"
@interface ResourceByte : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasKey_:1;
  BOOL hasExt_:1;
  BOOL hasValue_:1;
  NSString* key;
  NSString* ext;
  NSData* value;
}
- (BOOL) hasKey;
- (BOOL) hasValue;
- (BOOL) hasExt;
@property (readonly, strong) NSString* key;
@property (readonly, strong) NSData* value;
@property (readonly, strong) NSString* ext;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResourceByteBuilder*) builder;
+ (ResourceByteBuilder*) builder;
+ (ResourceByteBuilder*) builderWithPrototype:(ResourceByte*) prototype;
- (ResourceByteBuilder*) toBuilder;

+ (ResourceByte*) parseFromData:(NSData*) data;
+ (ResourceByte*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResourceByte*) parseFromInputStream:(NSInputStream*) input;
+ (ResourceByte*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResourceByte*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResourceByte*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ResourceByteBuilder : PBGeneratedMessageBuilder {
@private
  ResourceByte* resultResourceByte;
}

- (ResourceByte*) defaultInstance;

- (ResourceByteBuilder*) clear;
- (ResourceByteBuilder*) clone;

- (ResourceByte*) build;
- (ResourceByte*) buildPartial;

- (ResourceByteBuilder*) mergeFrom:(ResourceByte*) other;
- (ResourceByteBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResourceByteBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasKey;
- (NSString*) key;
- (ResourceByteBuilder*) setKey:(NSString*) value;
- (ResourceByteBuilder*) clearKey;

- (BOOL) hasValue;
- (NSData*) value;
- (ResourceByteBuilder*) setValue:(NSData*) value;
- (ResourceByteBuilder*) clearValue;

- (BOOL) hasExt;
- (NSString*) ext;
- (ResourceByteBuilder*) setExt:(NSString*) value;
- (ResourceByteBuilder*) clearExt;
@end


// @@protoc_insertion_point(global_scope)
