// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "SwAnimation.pb.h"
// @@protoc_insertion_point(imports)

@class Para;
@class ParaBuilder;
@class SignRectangle;
@class SignRectangleBuilder;
@class SwAnimation;
@class SwAnimationBuilder;
@class SwCompsiteAnimation;
@class SwCompsiteAnimationBuilder;
@class SwDesc;
@class SwDescBuilder;
@class SwFrame;
@class SwFrameBuilder;



@interface SwDescRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define SwDesc_packageName @"packageName"
#define SwDesc_list @"list"
@interface SwDesc : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPackageName_:1;
  NSString* packageName;
  NSMutableArray * listArray;
}
- (BOOL) hasPackageName;
@property (readonly, strong) NSString* packageName;
@property (readonly, strong) NSArray * list;
- (SwAnimation*)listAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SwDescBuilder*) builder;
+ (SwDescBuilder*) builder;
+ (SwDescBuilder*) builderWithPrototype:(SwDesc*) prototype;
- (SwDescBuilder*) toBuilder;

+ (SwDesc*) parseFromData:(NSData*) data;
+ (SwDesc*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwDesc*) parseFromInputStream:(NSInputStream*) input;
+ (SwDesc*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwDesc*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SwDesc*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SwDescBuilder : PBGeneratedMessageBuilder {
@private
  SwDesc* resultSwDesc;
}

- (SwDesc*) defaultInstance;

- (SwDescBuilder*) clear;
- (SwDescBuilder*) clone;

- (SwDesc*) build;
- (SwDesc*) buildPartial;

- (SwDescBuilder*) mergeFrom:(SwDesc*) other;
- (SwDescBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SwDescBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPackageName;
- (NSString*) packageName;
- (SwDescBuilder*) setPackageName:(NSString*) value;
- (SwDescBuilder*) clearPackageName;

- (NSMutableArray *)list;
- (SwAnimation*)listAtIndex:(NSUInteger)index;
- (SwDescBuilder *)addList:(SwAnimation*)value;
- (SwDescBuilder *)setListArray:(NSArray *)array;
- (SwDescBuilder *)clearList;
@end


// @@protoc_insertion_point(global_scope)
