// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class SwFrame;
@class SwFrameBuilder;



@interface SwFrameRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define SwFrame_v @"v"
#define SwFrame_x @"x"
#define SwFrame_y @"y"
#define SwFrame_t @"t"
#define SwFrame_mlist @"mlist"
@interface SwFrame : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasV_:1;
  BOOL hasX_:1;
  BOOL hasY_:1;
  BOOL hasT_:1;
  SInt32 v;
  SInt32 x;
  SInt32 y;
  SInt32 t;
  PBAppendableArray * mlistArray;
}
- (BOOL) hasV;
- (BOOL) hasX;
- (BOOL) hasY;
- (BOOL) hasT;
@property (readonly) SInt32 v;
@property (readonly) SInt32 x;
@property (readonly) SInt32 y;
@property (readonly) SInt32 t;
@property (readonly, strong) PBArray * mlist;
- (SInt32)mlistAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SwFrameBuilder*) builder;
+ (SwFrameBuilder*) builder;
+ (SwFrameBuilder*) builderWithPrototype:(SwFrame*) prototype;
- (SwFrameBuilder*) toBuilder;

+ (SwFrame*) parseFromData:(NSData*) data;
+ (SwFrame*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwFrame*) parseFromInputStream:(NSInputStream*) input;
+ (SwFrame*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwFrame*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SwFrame*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SwFrameBuilder : PBGeneratedMessageBuilder {
@private
  SwFrame* resultSwFrame;
}

- (SwFrame*) defaultInstance;

- (SwFrameBuilder*) clear;
- (SwFrameBuilder*) clone;

- (SwFrame*) build;
- (SwFrame*) buildPartial;

- (SwFrameBuilder*) mergeFrom:(SwFrame*) other;
- (SwFrameBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SwFrameBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasV;
- (SInt32) v;
- (SwFrameBuilder*) setV:(SInt32) value;
- (SwFrameBuilder*) clearV;

- (BOOL) hasX;
- (SInt32) x;
- (SwFrameBuilder*) setX:(SInt32) value;
- (SwFrameBuilder*) clearX;

- (BOOL) hasY;
- (SInt32) y;
- (SwFrameBuilder*) setY:(SInt32) value;
- (SwFrameBuilder*) clearY;

- (BOOL) hasT;
- (SInt32) t;
- (SwFrameBuilder*) setT:(SInt32) value;
- (SwFrameBuilder*) clearT;

- (PBAppendableArray *)mlist;
- (SInt32)mlistAtIndex:(NSUInteger)index;
- (SwFrameBuilder *)addMlist:(SInt32)value;
- (SwFrameBuilder *)setMlistArray:(NSArray *)array;
- (SwFrameBuilder *)setMlistValues:(const SInt32 *)values count:(NSUInteger)count;
- (SwFrameBuilder *)clearMlist;
@end


// @@protoc_insertion_point(global_scope)
